"""Interactive Streamlit dashboard for the Loblaw Bio clinical trial analysis.

Usage:
    streamlit run dashboard.py

Reads exclusively from clinical_trial.db and outputs/ generated by
load_data.py and analysis.py -- run `make pipeline` first.
"""

import html as html_lib
import sqlite3
import uuid
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

REPO_ROOT = Path(__file__).resolve().parent
DB_PATH = REPO_ROOT / "clinical_trial.db"
OUTPUTS_DIR = REPO_ROOT / "outputs"

POPULATIONS = ["b_cell", "cd8_t_cell", "cd4_t_cell", "nk_cell", "monocyte"]
POP_LABELS = {
    "b_cell": "B Cell", "cd8_t_cell": "CD8 T Cell", "cd4_t_cell": "CD4 T Cell",
    "nk_cell": "NK Cell", "monocyte": "Monocyte",
}

st.set_page_config(page_title="Loblaw Bio - Miraclib Trial Analysis", layout="wide")


@st.cache_resource
def get_connection() -> sqlite3.Connection:
    return sqlite3.connect(DB_PATH, check_same_thread=False)


@st.cache_data
def load_table(_conn, query: str, params: tuple = ()) -> pd.DataFrame:
    return pd.read_sql_query(query, _conn, params=params)


@st.cache_data
def load_csv(name: str) -> pd.DataFrame:
    return pd.read_csv(OUTPUTS_DIR / name)


def missing_pipeline_warning():
    st.error(
        "Pipeline outputs not found. Run `make pipeline` (or `python load_data.py "
        "&& python analysis.py`) before launching the dashboard."
    )
    st.stop()


def render_table(df: pd.DataFrame, max_body_height: int = 320, scrollable: bool = True) -> None:
    """Render a DataFrame as a searchable table with sortable column headers.

    Replaces st.dataframe's built-in column menu (sort/pin/autosize/hide/...)
    with just click-to-sort headers, plus a search box that filters rows
    across every column.
    """
    table_id = f"tbl_{uuid.uuid4().hex[:8]}"
    columns = list(df.columns)

    def display_and_sort(val):
        if pd.isna(val):
            return "", ""
        if isinstance(val, (int, float)) and not isinstance(val, bool):
            sort_val = repr(float(val))
            display = f"{val:,.4g}" if isinstance(val, float) else f"{val:,}"
            return html_lib.escape(display), sort_val
        text = str(val)
        return html_lib.escape(text), html_lib.escape(text.lower())

    header_cells = "".join(
        f'<th data-col="{i}"><span class="th-label">{html_lib.escape(str(col))}</span>'
        f'<span class="sort-arrow"></span></th>'
        for i, col in enumerate(columns)
    )

    body_rows = []
    for _, row in df.iterrows():
        cells = []
        for col in columns:
            display, sort_val = display_and_sort(row[col])
            cells.append(f'<td data-sort="{sort_val}">{display}</td>')
        body_rows.append(f"<tr>{''.join(cells)}</tr>")
    body_html = "".join(body_rows)

    n_rows = len(df)
    content_height = max(1, n_rows) * 38 + 4
    body_height = content_height if not scrollable else min(max_body_height, content_height)
    total_height = 56 + 40 + body_height + 20
    scroll_css = f"max-height: {body_height}px; overflow-y: auto;" if scrollable else "overflow-y: visible;"

    light_vars = (
        "--tbl-bg: #d5d6d8; --tbl-color: #262730; --tbl-hover-bg: #c3c4c7; "
        "--tbl-border: rgba(38, 39, 48, 0.2); --tbl-input-border: rgba(38, 39, 48, 0.25);"
    )
    dark_vars = (
        "--tbl-bg: #262730; --tbl-color: #fafafa; --tbl-hover-bg: #3b3b47; "
        "--tbl-border: rgba(250, 250, 250, 0.2); --tbl-input-border: rgba(250, 250, 250, 0.3);"
    )
    # st.context.theme.type reflects the app's actual active theme, including a
    # manual Light/Dark pick from Streamlit's settings menu (not just OS preference).
    theme_type = st.context.theme.type
    if theme_type == "dark":
        theme_css = f":root {{ {dark_vars} }}"
    elif theme_type == "light":
        theme_css = f":root {{ {light_vars} }}"
    else:
        # Theme not yet known (e.g. first render of the session) -- fall back
        # to OS preference until a rerun reports the real value.
        theme_css = f":root {{ {light_vars} }} @media (prefers-color-scheme: dark) {{ :root {{ {dark_vars} }} }}"

    page_html = f"""
    <div id="{table_id}" class="table-wrap">
      <style>
        {theme_css}
        .table-wrap {{
          font-family: "Source Sans Pro", -apple-system, BlinkMacSystemFont, sans-serif;
          font-size: 14px;
          color: var(--tbl-color);
        }}
        .table-wrap .search-input {{
          box-sizing: border-box;
          width: 100%;
          padding: 6px 10px;
          margin-bottom: 8px;
          border: 1px solid var(--tbl-input-border);
          border-radius: 0.5rem;
          font-size: 14px;
          outline: none;
        }}
        .table-wrap .search-input:focus {{
          border-color: #ff4b4b;
        }}
        .table-wrap .table-scroll {{
          {scroll_css}
          border: 1px solid var(--tbl-border);
        }}
        .table-wrap table {{
          width: 100%;
          border-collapse: collapse;
        }}
        .table-wrap thead th {{
          position: sticky;
          top: 0;
          background: var(--tbl-bg);
          color: var(--tbl-color);
          font-weight: 700;
          text-align: left;
          padding: 8px 10px;
          cursor: pointer;
          user-select: none;
          white-space: nowrap;
          border-bottom: 1px solid var(--tbl-border);
        }}
        .table-wrap thead th:hover {{
          background: var(--tbl-hover-bg);
        }}
        .table-wrap .sort-arrow {{
          margin-left: 4px;
          font-size: 11px;
          color: #ff4b4b;
        }}
        .table-wrap tbody td {{
          background: var(--tbl-bg);
          color: var(--tbl-color);
          font-weight: 400;
          padding: 7px 10px;
          border-bottom: 1px solid var(--tbl-border);
          white-space: nowrap;
        }}
        .table-wrap tbody tr:hover td {{
          background: var(--tbl-hover-bg);
        }}
      </style>
      <input class="search-input" type="text" placeholder="Search..." />
      <div class="table-scroll">
        <table>
          <thead><tr>{header_cells}</tr></thead>
          <tbody>{body_html}</tbody>
        </table>
      </div>
    </div>
    <script>
    (function() {{
      const root = document.getElementById("{table_id}");
      const table = root.querySelector("table");
      const tbody = table.querySelector("tbody");
      const searchInput = root.querySelector(".search-input");
      const headers = table.querySelectorAll("th");

      searchInput.addEventListener("input", function() {{
        const q = this.value.trim().toLowerCase();
        tbody.querySelectorAll("tr").forEach(function(tr) {{
          tr.style.display = tr.textContent.toLowerCase().includes(q) ? "" : "none";
        }});
      }});

      let sortState = {{col: null, dir: 1}};
      headers.forEach(function(th) {{
        th.addEventListener("click", function() {{
          const col = parseInt(th.dataset.col, 10);
          const dir = (sortState.col === col) ? -sortState.dir : 1;
          sortState = {{col: col, dir: dir}};
          headers.forEach(function(h) {{ h.querySelector(".sort-arrow").textContent = ""; }});
          th.querySelector(".sort-arrow").textContent = dir === 1 ? "\\u25B2" : "\\u25BC";

          const rows = Array.from(tbody.querySelectorAll("tr"));
          rows.sort(function(a, b) {{
            const av = a.children[col].dataset.sort;
            const bv = b.children[col].dataset.sort;
            const an = parseFloat(av), bn = parseFloat(bv);
            let cmp;
            if (av !== "" && bv !== "" && !isNaN(an) && !isNaN(bn)) {{
              cmp = an - bn;
            }} else {{
              cmp = av.localeCompare(bv);
            }}
            return cmp * dir;
          }});
          rows.forEach(function(r) {{ tbody.appendChild(r); }});
        }});
      }});
    }})();

    (function() {{
      // Live-sync with Streamlit's actual active theme (including a manual
      // Light/Dark pick from Streamlit's own settings menu), without needing
      // a Python-side rerun. Streamlit's html component iframe is sandboxed
      // with allow-same-origin, so window.parent is reachable directly.
      var LIGHT = {{
        bg: "#d5d6d8", color: "#262730", hover: "#c3c4c7",
        border: "rgba(38, 39, 48, 0.2)", inputBorder: "rgba(38, 39, 48, 0.25)"
      }};
      var DARK = {{
        bg: "#262730", color: "#fafafa", hover: "#3b3b47",
        border: "rgba(250, 250, 250, 0.2)", inputBorder: "rgba(250, 250, 250, 0.3)"
      }};

      function parentIsDark() {{
        try {{
          var pdoc = window.parent.document;
          var el = pdoc.querySelector(".stApp") || pdoc.body;
          var bg = window.parent.getComputedStyle(el).backgroundColor;
          var m = bg.match(/[\\d.]+/g);
          if (!m || m.length < 3) return null;
          var luminance = 0.299 * m[0] + 0.587 * m[1] + 0.114 * m[2];
          return luminance < 128;
        }} catch (e) {{
          return null;
        }}
      }}

      function applyTheme() {{
        var dark = parentIsDark();
        if (dark === null) return;
        var vars = dark ? DARK : LIGHT;
        var style = document.documentElement.style;
        style.setProperty("--tbl-bg", vars.bg);
        style.setProperty("--tbl-color", vars.color);
        style.setProperty("--tbl-hover-bg", vars.hover);
        style.setProperty("--tbl-border", vars.border);
        style.setProperty("--tbl-input-border", vars.inputBorder);
      }}

      applyTheme();
      setInterval(applyTheme, 500);
    }})();
    </script>
    """
    st.components.v1.html(page_html, height=total_height, scrolling=False)


def inject_kpi_style() -> None:
    """Give every st.metric a visible grey card background, in light or dark mode."""
    light_bg = "#d5d6d8"
    dark_bg = "#262730"
    theme_type = st.context.theme.type
    if theme_type == "dark":
        theme_css = f":root {{ --kpi-bg: {dark_bg}; }}"
    elif theme_type == "light":
        theme_css = f":root {{ --kpi-bg: {light_bg}; }}"
    else:
        theme_css = (
            f":root {{ --kpi-bg: {light_bg}; }} "
            f"@media (prefers-color-scheme: dark) {{ :root {{ --kpi-bg: {dark_bg}; }} }}"
        )

    st.html(
        f"""
        <style>
        {theme_css}
        div[data-testid="stMetric"] {{
          background: var(--kpi-bg);
          border-radius: 0.5rem;
          padding: 1rem 1rem 0.75rem 1rem;
        }}
        </style>
        <script>
        (function() {{
          function isDark() {{
            try {{
              var el = document.querySelector(".stApp") || document.body;
              var bg = getComputedStyle(el).backgroundColor;
              var m = bg.match(/[\\d.]+/g);
              if (!m || m.length < 3) return null;
              return (0.299 * m[0] + 0.587 * m[1] + 0.114 * m[2]) < 128;
            }} catch (e) {{
              return null;
            }}
          }}
          function apply() {{
            var dark = isDark();
            if (dark === null) return;
            document.documentElement.style.setProperty(
              "--kpi-bg", dark ? "{dark_bg}" : "{light_bg}"
            );
          }}
          apply();
          if (!window.__kpiThemeSyncRunning) {{
            window.__kpiThemeSyncRunning = true;
            setInterval(apply, 500);
          }}
        }})();
        </script>
        """,
        unsafe_allow_javascript=True,
    )


if not DB_PATH.exists() or not (OUTPUTS_DIR / "summary_table.csv").exists():
    missing_pipeline_warning()

conn = get_connection()
inject_kpi_style()

st.title("Loblaw Bio: Miraclib Clinical Trial Analysis")
st.caption("Immune cell population analysis for Bob Loblaw's melanoma miraclib trial")

tab1, tab2, tab3 = st.tabs(["Data Overview", "Treatment Response", "Baseline Analysis"])

# ---------------------------------------------------------------------------
# Tab 1: Data Overview
# ---------------------------------------------------------------------------
with tab1:
    st.header("Data Overview")

    n_projects = load_table(conn, "SELECT COUNT(*) AS n FROM projects").iloc[0, 0]
    n_subjects = load_table(conn, "SELECT COUNT(*) AS n FROM subjects").iloc[0, 0]
    n_samples = load_table(conn, "SELECT COUNT(*) AS n FROM samples").iloc[0, 0]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Projects", n_projects)
    c2.metric("Subjects", n_subjects)
    c3.metric("Samples", n_samples)
    c4.metric("Populations", len(POPULATIONS))

    st.subheader("Explore a sample")
    samples = load_table(conn, "SELECT sample_id FROM samples ORDER BY sample_id")["sample_id"].tolist()
    selected_sample = st.selectbox("Sample", samples)

    sample_df = load_table(
        conn,
        "SELECT population, count, percentage, total_count FROM population_frequencies "
        "WHERE sample = ? ORDER BY population",
        params=(selected_sample,),
    )
    sample_df["population"] = sample_df["population"].map(POP_LABELS)

    col_a, col_b = st.columns([1, 1])
    with col_a:
        render_table(
            sample_df[["population", "count", "percentage"]].rename(
                columns={"population": "Population", "count": "Cell count", "percentage": "Relative frequency (%)"}
            )
        )
        st.caption(f"Total cell count: {int(sample_df['total_count'].iloc[0]):,}")
    with col_b:
        fig = px.pie(sample_df, names="population", values="count", hole=0.5,
                     title=f"Population composition — {selected_sample}")
        st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------------------------------
# Tab 2: Treatment Response (Part 3)
# ---------------------------------------------------------------------------
with tab2:
    st.header("Treatment Response: Melanoma / Miraclib / PBMC")
    st.caption("Responder vs non-responder comparison of immune cell relative frequencies")

    stats_df = load_csv("statistical_results.csv")

    plot_path = OUTPUTS_DIR / "plots" / "responder_boxplots.html"
    if plot_path.exists():
        st.components.v1.html(plot_path.read_text(encoding="utf-8"), height=600, scrolling=True)

    st.subheader("Statistical results")
    pop_choice = st.selectbox(
        "Population", POPULATIONS, format_func=lambda p: POP_LABELS[p], key="pop_choice"
    )
    row = stats_df[stats_df["population"] == pop_choice].iloc[0]

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Responder n", int(row["responder_n"]))
    m2.metric("Non-responder n", int(row["non_responder_n"]))
    m3.metric("Responder median", f"{row['responder_median']:.2f}%")
    m4.metric("Non-responder median", f"{row['non_responder_median']:.2f}%")

    m5, m6, m7 = st.columns(3)
    m5.metric("p-value", f"{row['p_value']:.4g}")
    m6.metric("Adjusted p-value (BH)", f"{row['adjusted_p_value']:.4g}")
    m7.metric("Significant (alpha=0.05)", "Yes" if row["significant"] else "No")

    st.subheader("All populations")
    display_stats = stats_df.copy()
    display_stats["population"] = display_stats["population"].map(POP_LABELS)
    render_table(display_stats)

    st.info(
        "**Interpretation note:** this is a sample-level exploratory analysis. Subjects "
        "contribute up to three longitudinal samples each, so observations are not fully "
        "independent, and a significant association here should not be read as proof that "
        "a population predicts treatment response."
    )

# ---------------------------------------------------------------------------
# Tab 3: Baseline Analysis (Part 4)
# ---------------------------------------------------------------------------
with tab3:
    st.header("Baseline Analysis: Melanoma / PBMC / Miraclib, Day 0")

    baseline_df = load_csv("baseline_samples.csv")

    by_project = baseline_df[baseline_df["breakdown"] == "samples_by_project"]
    by_response = baseline_df[baseline_df["breakdown"] == "subjects_by_response"]
    by_sex = baseline_df[baseline_df["breakdown"] == "subjects_by_sex"]

    col1, col2, col3 = st.columns(3)
    with col1:
        st.subheader("Samples by project")
        fig1 = go.Figure(go.Bar(x=by_project["group_value"], y=by_project["value"]))
        fig1.update_layout(xaxis_title="Project", yaxis_title="Number of samples", height=400)
        st.plotly_chart(fig1, use_container_width=True)
        render_table(by_project[["group_value", "value"]].rename(
            columns={"group_value": "Project", "value": "Sample count"}), scrollable=False)

    with col2:
        st.subheader("Subjects by response")
        fig2 = go.Figure(go.Bar(x=by_response["group_value"], y=by_response["value"]))
        fig2.update_layout(xaxis_title="Response", yaxis_title="Number of subjects", height=400)
        st.plotly_chart(fig2, use_container_width=True)
        render_table(by_response[["group_value", "value"]].rename(
            columns={"group_value": "Response", "value": "Subject count"}), scrollable=False)

    with col3:
        st.subheader("Subjects by sex")
        fig3 = go.Figure(go.Bar(x=by_sex["group_value"], y=by_sex["value"]))
        fig3.update_layout(xaxis_title="Sex", yaxis_title="Number of subjects", height=400)
        st.plotly_chart(fig3, use_container_width=True)
        render_table(by_sex[["group_value", "value"]].rename(
            columns={"group_value": "Sex", "value": "Subject count"}), scrollable=False)
